### DISCUSSION TITLE
PCL2-homepage-collection 自定义主页 CDN 托管

### DISCUSSION THREAD

**Discussion by z0z0r4** [Meloong-Git/PCL#5193] [自定义主页]
为了降低自定义主页的维护成本，将在 @pysio2007 的支持下开放自定义主页 CDN 托管服务，此 collection 将维护一个统一的 CDN 供主页作者使用，无需为维护和潜在的攻击风险担心。

有兴趣的自定义主页作者可以前往 [PCL2-homepage-collection](https://github.com/z0z0r4/PCL2-homepage-collection) 查看详情。

主页作者可以提供一个可以被 GitHub Action 访问的 url（例如 GitHub 文件、最新 Release 直链），并在 issue 申请收录（参考 https://github.com/Hex-Dragon/PCL2/discussions/2528 提供信息）。

示例：https://pcl2-homepage.pysio.online/PCL2_update_logging/homepage.xaml

```yaml
- description: 'PCL2更新日志'
  homepage_link: 'https://github.com/Joker2184/UpdateHomepage'
  homepage_name: 'PCL2_update_logging'
  owner: 'Joker2184'
  owner_link: 'https://github.com/Joker2184'
  source_url: 'https://updatehomepage.pages.dev/UpdateHomepage.xaml'
```
